source "https://rubygems.org"

gem "sinatra"
gem "sequel"
gem "haml", "~> 5.2.2"
gem "yaml"
gem "erb"
gem "cgi"
gem "sqlite3"
gem "bcrypt"
gem "add_to_calendar"
gem "prawn"
gem "rmagick"
gem "rackup", "~> 2.2"
gem "puma", "~> 7.1"
gem "net-smtp"
gem "twilio-ruby"
gem "rack-protection"
gem "rb-inotify"